# Generated by Django 3.0.7 on 2020-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeEmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('initiation_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BoxList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_num', models.IntegerField()),
                ('available', models.BooleanField()),
                ('associated_customer', models.EmailField(max_length=254)),
                ('filledTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('box_num', models.CharField(max_length=200)),
                ('entrance_time', models.DateTimeField()),
                ('access_code', models.IntegerField()),
            ],
        ),
    ]
