# Generated by Django 3.0.7 on 2020-07-19 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeemailverification',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='beforeemailverification',
            name='initiation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
