# Generated by Django 3.0.7 on 2020-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlist',
            name='associated_customer',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='filledTime',
            field=models.DateTimeField(null=True),
        ),
    ]
