# Generated by Django 3.0.7 on 2020-07-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200719_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeemailverification',
            name='expire_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='beforeemailverification',
            name='initiation_time',
            field=models.DateTimeField(),
        ),
    ]
