# Generated by Django 3.0.7 on 2020-07-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parcel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='entered_date',
            new_name='entrance_time',
        ),
    ]
