# Generated by Django 3.0.7 on 2020-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_beforeemailverification_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='box_num',
            field=models.CharField(max_length=200),
        ),
    ]
