# Generated by Django 3.0.7 on 2020-07-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200723_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxlist',
            name='associeted_customer',
        ),
        migrations.AddField(
            model_name='boxlist',
            name='associated_customer',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='filledTime',
            field=models.DateTimeField(null=True),
        ),
    ]
