# Generated by Django 3.0.7 on 2020-07-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200724_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlist',
            name='associated_customer',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='filledTime',
            field=models.DateTimeField(null=True),
        ),
    ]
