# Generated by Django 3.0.7 on 2020-07-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200724_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlist',
            name='associated_customer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='boxlist',
            name='filledTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
